spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testing_db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=tru
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  session:

    timeout: 15m
    jdbc:
      initialize-schema: always

