name: WebsiteCloud
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - WebsiteCloudNet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    container_name: spring_boot_app
    environment:
      DB_HOST: "db"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - WebsiteCloudNet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - WebsiteCloudNet
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:

networks:
  WebsiteCloudNet:
    driver: bridge